const comment =
  '// Autogenerated file, DO NOT MODIFY or it will be overwritten';

const template = (variables, { tpl }) => {
  const componentName = variables.componentName.replace('Svg', '');
  return tpl`
${comment}
${variables.imports};

${variables.interfaces};

const Svg = (${variables.props}) => (
  ${variables.jsx}
);

const ${componentName} = (props: SVGProps<SVGSVGElement>) => {
  return <Svg fill="currentColor" {...props} />;
};

export default ${componentName};
`;
};

// eslint-disable-next-line no-undef
module.exports = {
  icon: true,
  outDir: './src/platform/components/icons/generated',
  filenameCase: 'kebab',
  expandProps: true,
  typescript: true,
  replaceAttrValues: { '#000': 'currentColor' },
  template,
  svgoConfig: {
    plugins: [{ name: 'preset-default' }, 'prefixIds'],
  },

  // See https://github.com/gregberge/svgr/issues/893 for details on the underlying issue
  prettier: false,
};
