const comment =
  '// Autogenerated file, DO NOT MODIFY or it will be overwritten';

const template = (variables, { tpl }) => {
  const componentName = variables.componentName.replace('Svg', '');
  return tpl`
${comment}
${variables.imports};

${variables.interfaces};

const Svg = (${variables.props}) => (
  ${variables.jsx}
);

const ${componentName} = (props: SVGProps<SVGSVGElement>) => {
  return <Svg fill="currentColor" {...props} />;
};

export default ${componentName};
`;
};

// eslint-disable-next-line no-undef
module.exports = {
  icon: true,
  outDir: './src/components/icons/generated',
  expandProps: true,
  typescript: true,
  replaceAttrValues: { '#000': 'currentColor' },
  template,

  // Prevent svgr + prettier 3 compatibility issue
  // It is ok to disable it here, generation script will run prettier
  // See https://github.com/gregberge/svgr/issues/893 for details on the underlying issue
  prettier: false,
};
