name: 🔎 Code Quality

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  format:
    name: Format
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 24

      - name: Check formatting
        run: pnpm format:check

      - name: Ensure formatting check did not mutate files
        run: git diff --exit-code -- .

  check:
    name: Static Check
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 24

      - name: Run static checks
        run: pnpm check:ci

      - name: Ensure static checks did not mutate files
        run: git diff --exit-code -- .

  tests:
    name: Tests
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      VITE_BASE_URL: http://localhost:3000
      VITE_S3_BUCKET_PUBLIC_URL: 'http://localhost:9000/default'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 24

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run tests
        run: SKIP_ENV_VALIDATION=true pnpm test:coverage

      - name: Upload coverage to Codecov
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@cddd853df119a48c5be31a973f8cd97e12e35e16 # v6.0.1
        with:
          files: ./coverage/lcov.info
          flags: vitest
          name: vitest
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
      VITE_BASE_URL: http://localhost:3000
      VITE_S3_BUCKET_PUBLIC_URL: 'http://localhost:9000/default'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 24

      - name: Build app
        run: pnpm build
