on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - master
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 16 3 * * *
name: Semgrep

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    name: Semgrep
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: semgrep/semgrep@sha256:7cad2bc2d1e44f87f0bf4be6d1fa23aa90fb72015bebc89fb91385d813987a03
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Semgrep
        run: semgrep scan --config .semgrep.yml --error --quiet --sarif-output semgrep.sarif

      - name: Upload Semgrep SARIF
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: semgrep-sarif
          path: semgrep.sarif
          retention-days: 30
